build:
  maxIssues: 0

naming:
  FunctionNaming:
    active: true
    excludes: 
      - '**/*Composable.kt'
      - '**/*Activity.kt'
      - '**/*Screen.kt'
      - '**/*Field.kt'
      - '**/*Bubble.kt'
      - '**/*Bar.kt'

style:
  MagicNumber:
    excludeAnnotated: ["Composable"]
    active: true
    excludes: 
      - '**/ui/theme/*.kt'
  NewLineAtEndOfFile:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 120

complexity:
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 5
    constructorThreshold: 5