build:
  maxIssues: 0

naming:
  FunctionNaming:
    active: true
    excludes: 
      - "**/*Composable.kt"
      - "**/*Activity.kt"
      - "**/*Screen.kt"

style:
  NewLineAtEndOfFile:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 120

complexity:
  LongMethod:
    active: true
    threshold: 30
  LongParameterList:
    active: true
    functionThreshold: 5
    constructorThreshold: 5