name: Release

on:
  workflow_dispatch:
    paths:
      -'client/**'
      -'.github/workflows/release.yml'

jobs:
  build-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build Release
        run: ./gradlew assembleRelease
      - uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
